[package]
name = "rust-jwt-test"
version = "0.1.0"
authors = ["marcelolecar"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frank_jwt = "3.1.2"
serde_json = "1.0.61"
